# Generated by Django 4.2.30 on 2026-07-30 19:13, envolvida manualmente em
# SeparateDatabaseAndState: os models já existem fisicamente nas tabelas
# legislativo_* (movidos do app legislativo) — aqui só o ESTADO do Django é
# atualizado, nenhuma DDL real roda (database_operations=[]).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name="EdicaoMeritoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=64)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Histórico de edição de mérito",
                "verbose_name_plural": "Históricos de edição de mérito",
                "db_table": "legislativo_edicaomeritohistorico",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Macrotema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("cor", models.CharField(default="#000000", max_length=7)),
            ],
            options={
                "verbose_name": "Macrotema",
                "verbose_name_plural": "Macrotemas",
                "db_table": "legislativo_macrotema",
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "macrotema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temas",
                        to="proposicoes.macrotema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
                "db_table": "legislativo_tema",
            },
        ),
        migrations.CreateModel(
            name="Proposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=1024)),
                (
                    "casa",
                    models.CharField(
                        choices=[("camara", "Câmara"), ("senado", "Senado")],
                        max_length=32,
                    ),
                ),
                ("status_tramitacao", models.CharField(blank=True, max_length=128)),
                ("local", models.CharField(blank=True, max_length=128)),
                ("pauta", models.BooleanField(default=False)),
                ("urgente", models.BooleanField(default=False)),
                ("aprovada", models.BooleanField(default=False)),
                ("parada", models.BooleanField(default=False)),
                (
                    "prioridade_fnp",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("ementa_resumida", models.TextField(blank=True)),
                ("proximos_eventos", models.TextField(blank=True)),
                ("interlocutores", models.TextField(blank=True)),
                ("ultima_movimentacao", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("posicionamento_fnp", models.TextField(blank=True)),
                ("acoes_incidencia", models.TextField(blank=True)),
                ("riscos_oportunidades", models.TextField(blank=True)),
                ("visualizacoes", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "macrotema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposicoes",
                        to="proposicoes.macrotema",
                    ),
                ),
                (
                    "temas",
                    models.ManyToManyField(
                        blank=True,
                        db_table="legislativo_proposicao_temas",
                        related_name="proposicoes",
                        to="proposicoes.tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposição",
                "verbose_name_plural": "Proposições",
                "db_table": "legislativo_proposicao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=512)),
                ("resumo", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "proposicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noticias",
                        to="proposicoes.proposicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
                "db_table": "legislativo_noticia",
                "ordering": ["-publicado_em"],
            },
        ),
        ],
        database_operations=[],
      ),
    ]
