# Generated by Django 4.2.30 on 2026-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposicoes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
