# Generated by Django 5.2.17 on 2026-08-18 20:03

import apps.proposicoes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposicoes", "0003_alter_noticia_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoProposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="anexos_proposicoes/%Y/%m/",
                        validators=[
                            apps.proposicoes.models.validar_tamanho_anexo,
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            ),
                        ],
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anexos_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="proposicoes.proposicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo da proposição",
                "verbose_name_plural": "Anexos da proposição",
                "ordering": ["-criado_em"],
            },
        ),
    ]
