# Generated by Django 5.2.17 on 2026-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposicoes", "0004_anexoproposicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexoproposicao",
            name="status_moderacao",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=16,
            ),
        ),
    ]
