# Generated by Django 4.2.30 on 2026-07-30 19:13, envolvida manualmente em
# SeparateDatabaseAndState: os models já existem fisicamente nas tabelas
# legislativo_* (movidos do app legislativo) — aqui só o ESTADO do Django é
# atualizado, nenhuma DDL real roda (database_operations=[]).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "status_moderacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=16,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "db_table": "legislativo_comentario",
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Participacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cadastro", "Cadastro"),
                            ("sugestao", "Sugestão"),
                            ("indicacao", "Indicação"),
                            ("duvida", "Dúvida"),
                        ],
                        max_length=16,
                    ),
                ),
                ("municipio", models.CharField(max_length=255)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("proposicao", models.CharField(blank=True, max_length=512)),
                ("responsavel", models.CharField(max_length=255)),
                ("cargo", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=64)),
                ("mensagem", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Participação",
                "verbose_name_plural": "Participações",
                "db_table": "legislativo_participacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.CharField(max_length=255)),
                ("lida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="comentarios.comentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "legislativo_notificacao",
                "ordering": ["-criado_em"],
            },
        ),
        ],
        database_operations=[],
      ),
    ]
