# Generated by Django 4.2.30 on 2026-07-30 19:13, envolvida manualmente em
# SeparateDatabaseAndState: as colunas já existem fisicamente nas tabelas
# legislativo_comentario/legislativo_notificacao — aqui só o ESTADO do
# Django é atualizado, nenhuma DDL real roda (database_operations=[]).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proposicoes", "0001_initial"),
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="notificacao",
                    name="destinatario",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="notificacao",
                    name="proposicao",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="proposicoes.proposicao",
                    ),
                ),
                migrations.AddField(
                    model_name="comentario",
                    name="autor",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="comentario",
                    name="parent",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="comentarios.comentario",
                    ),
                ),
                migrations.AddField(
                    model_name="comentario",
                    name="proposicao",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="proposicoes.proposicao",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
