# Generated by Django 4.2.30 on 2026-07-31 15:34
#
# A tabela física (legislativo_participacao) foi criada de verdade só em
# legislativo.0001_initial — comentarios.0001/0002_initial são estado-only
# (SeparateDatabaseAndState, sem DDL real, ver comentários lá). Esta migração
# roda ALTER TABLE de verdade pela primeira vez neste app, por isso precisa
# depender explicitamente de legislativo.0001_initial para garantir que a
# tabela já exista ao (re)criar o banco do zero (ex.: banco de testes).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0002_initial"),
        ("legislativo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participacao",
            old_name="responsavel",
            new_name="setor_responsavel",
        ),
        migrations.RenameField(
            model_name="participacao",
            old_name="whatsapp",
            new_name="telefone",
        ),
    ]
