# Generated by Django 4.2.30 on 2026-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comentarios",
            "0003_rename_responsavel_participacao_setor_responsavel_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PalavraProibida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palavra", models.CharField(max_length=100, unique=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Palavra proibida",
                "verbose_name_plural": "Palavras proibidas",
                "ordering": ["palavra"],
            },
        ),
    ]
