# Generated by Django 4.2.30 on 2026-07-31 18:07
#
# As tabelas físicas legislativo_usuario/legislativo_comentario (alvo das FKs
# denunciante/comentario abaixo) foram criadas de verdade em
# legislativo.0001_initial — swappable_dependency(AUTH_USER_MODEL) só garante
# o ESTADO (resolve pra usuarios.0001_initial, que é SeparateDatabaseAndState
# sem DDL real). Sem a dependência explícita abaixo, um banco criado do zero
# (ex.: Postgres de produção) pode tentar rodar esta migração ANTES da tabela
# legislativo_usuario existir de verdade — SQLite não valida isso no CREATE
# TABLE, então o bug não aparecia em dev/testes (mesmo problema documentado
# em usuarios.0002_perfil_status_aprovacao).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comentarios", "0004_palavraproibida"),
        ("legislativo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenunciaComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias",
                        to="comentarios.comentario",
                    ),
                ),
                (
                    "denunciante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia de comentário",
                "verbose_name_plural": "Denúncias de comentário",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="denunciacomentario",
            constraint=models.UniqueConstraint(
                fields=("comentario", "denunciante"), name="denuncia_unica_por_usuario"
            ),
        ),
    ]
