# Generated by Django 4.2.30 on 2026-07-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comentarios", "0004_palavraproibida"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenunciaComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias",
                        to="comentarios.comentario",
                    ),
                ),
                (
                    "denunciante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia de comentário",
                "verbose_name_plural": "Denúncias de comentário",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="denunciacomentario",
            constraint=models.UniqueConstraint(
                fields=("comentario", "denunciante"), name="denuncia_unica_por_usuario"
            ),
        ),
    ]
