# Generated by Django 5.2.17 on 2026-08-18 20:07

import apps.comentarios.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0007_comentariolike"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="midia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comentarios_midia/%Y/%m/",
                validators=[
                    apps.comentarios.models.validar_tamanho_midia_comentario,
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "mp4", "webm", "mov"]
                    ),
                ],
            ),
        ),
    ]
