# Generated by Django 5.2.17 on 2026-08-19 18:37

import apps.comentarios.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0008_comentario_midia"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="midia_tipo",
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="midia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comentarios_midia/%Y/%m/",
                validators=[
                    apps.comentarios.models.validar_tamanho_midia_comentario,
                    django.core.validators.FileExtensionValidator(
                        [
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "webm",
                            "mov",
                            "mp3",
                            "wav",
                            "ogg",
                            "m4a",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    ),
                ],
            ),
        ),
    ]
