# Generated by Django 5.2.17 on 2026-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0009_comentario_midia_tipo_alter_comentario_midia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="texto",
            field=models.TextField(blank=True),
        ),
    ]
