# Generated by Django 4.2.30 on 2026-07-30 19:13, envolvida manualmente em
# SeparateDatabaseAndState: os models já existem fisicamente nas tabelas
# legislativo_usuario/legislativo_municipio/legislativo_perfil (movidos do
# app legislativo) — aqui só o ESTADO do Django é atualizado, nenhuma DDL
# real roda (database_operations=[]).

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Usuario",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("password", models.CharField(max_length=128, verbose_name="password")),
                        (
                            "last_login",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="last login"
                            ),
                        ),
                        (
                            "is_superuser",
                            models.BooleanField(
                                default=False,
                                help_text="Designates that this user has all permissions without explicitly assigning them.",
                                verbose_name="superuser status",
                            ),
                        ),
                        (
                            "username",
                            models.CharField(
                                error_messages={
                                    "unique": "A user with that username already exists."
                                },
                                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                                max_length=150,
                                unique=True,
                                validators=[
                                    django.contrib.auth.validators.UnicodeUsernameValidator()
                                ],
                                verbose_name="username",
                            ),
                        ),
                        (
                            "first_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="first name"
                            ),
                        ),
                        (
                            "last_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="last name"
                            ),
                        ),
                        (
                            "email",
                            models.EmailField(
                                blank=True, max_length=254, verbose_name="email address"
                            ),
                        ),
                        (
                            "is_staff",
                            models.BooleanField(
                                default=False,
                                help_text="Designates whether the user can log into this admin site.",
                                verbose_name="staff status",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                                verbose_name="active",
                            ),
                        ),
                        (
                            "date_joined",
                            models.DateTimeField(
                                default=django.utils.timezone.now, verbose_name="date joined"
                            ),
                        ),
                        (
                            "groups",
                            models.ManyToManyField(
                                blank=True,
                                db_table="legislativo_usuario_groups",
                                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.group",
                                verbose_name="groups",
                            ),
                        ),
                        (
                            "user_permissions",
                            models.ManyToManyField(
                                blank=True,
                                db_table="legislativo_usuario_user_permissions",
                                help_text="Specific permissions for this user.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.permission",
                                verbose_name="user permissions",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Usuário",
                        "verbose_name_plural": "Usuários",
                        "db_table": "legislativo_usuario",
                    },
                    managers=[
                        ("objects", django.contrib.auth.models.UserManager()),
                    ],
                ),
                migrations.CreateModel(
                    name="Municipio",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("nome", models.CharField(max_length=255)),
                        ("uf", models.CharField(max_length=2)),
                        ("slug", models.SlugField(unique=True)),
                        ("prefeito", models.CharField(blank=True, max_length=255)),
                        ("populacao", models.PositiveIntegerField(blank=True, null=True)),
                    ],
                    options={
                        "verbose_name": "Município",
                        "verbose_name_plural": "Municípios",
                        "db_table": "legislativo_municipio",
                    },
                ),
                migrations.CreateModel(
                    name="Perfil",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("telefone", models.CharField(blank=True, max_length=32)),
                        ("cargo", models.CharField(blank=True, max_length=255)),
                        (
                            "municipio",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="perfil",
                                to="usuarios.municipio",
                            ),
                        ),
                        (
                            "usuario",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="perfil",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Perfil",
                        "verbose_name_plural": "Perfis",
                        "db_table": "legislativo_perfil",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
