# Generated by Django 4.2.30 on 2026-07-31 13:10
#
# A tabela física (legislativo_perfil) foi criada de verdade em
# legislativo.0005_usuario_perfil_split — usuarios.0001_initial é
# estado-only (SeparateDatabaseAndState, sem DDL real). Esta migração roda
# ALTER TABLE de verdade, por isso depende explicitamente da migração que
# criou a tabela, garantindo a ordem correta ao (re)criar o banco do zero
# (ex.: banco de testes).

from django.db import migrations, models


def aprovar_cadastros_existentes(apps, schema_editor):
    """Perfis já existentes correspondem a usuários já ativos no sistema —
    não devem ser bloqueados retroativamente pelo novo gate de aprovação."""
    Perfil = apps.get_model("usuarios", "Perfil")
    Perfil.objects.update(status_aprovacao="aprovado")


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        ("legislativo", "0005_usuario_perfil_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="status_aprovacao",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=16,
            ),
        ),
        migrations.RunPython(aprovar_cadastros_existentes, migrations.RunPython.noop),
    ]
