# Generated by Django 4.2.30 on 2026-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_perfil_status_aprovacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="exclusao_solicitada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto_google_url",
            field=models.URLField(blank=True),
        ),
    ]
