# Generated by Django 4.2.30 on 2026-07-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_perfil_exclusao_solicitada_em_perfil_foto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="setor_responsavel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfis",
                to="usuarios.municipio",
            ),
        ),
    ]
