# Generated by Django 5.2.17 on 2026-08-06 17:39

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_perfil_setor_responsavel_alter_perfil_municipio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[apps.usuarios.models.validar_tamanho_foto_perfil],
            ),
        ),
    ]
