# Generated by Django 5.2.17 on 2026-08-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_perfil_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativaLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255)),
                ("sucesso", models.BooleanField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tentativas_login",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa de login",
                "verbose_name_plural": "Tentativas de login",
                "db_table": "legislativo_tentativa_login",
                "ordering": ["-criado_em"],
            },
        ),
    ]
