# Generated by Django 5.2.17 on 2026-08-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_tentativalogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="classe_usuario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equipe_fnp", "Equipe FNP"),
                    ("prefeito", "Prefeito"),
                    ("indicado_prefeitura", "Indicado da prefeitura"),
                    ("parlamentar", "Parlamentar"),
                ],
                max_length=32,
            ),
        ),
    ]
