# Generated by Django 4.2.30 on 2026-07-29 14:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=32)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Macrotema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cor', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Macrotema',
                'verbose_name_plural': 'Macrotemas',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('slug', models.SlugField(unique=True)),
                ('prefeito', models.CharField(blank=True, max_length=255)),
                ('populacao', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('sugestao', 'Sugestão'), ('indicacao', 'Indicação'), ('duvida', 'Dúvida')], max_length=16)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('proposicao', models.CharField(blank=True, max_length=512)),
                ('responsavel', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=64)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('macrotema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='legislativo.macrotema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1024)),
                ('casa', models.CharField(choices=[('camara', 'Câmara'), ('senado', 'Senado')], max_length=32)),
                ('status_tramitacao', models.CharField(blank=True, max_length=128)),
                ('local', models.CharField(blank=True, max_length=128)),
                ('pauta', models.BooleanField(default=False)),
                ('urgente', models.BooleanField(default=False)),
                ('aprovada', models.BooleanField(default=False)),
                ('parada', models.BooleanField(default=False)),
                ('prioridade_fnp', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa'), ('normal', 'Normal')], default='normal', max_length=16)),
                ('ementa_resumida', models.TextField(blank=True)),
                ('proximos_eventos', models.TextField(blank=True)),
                ('interlocutores', models.TextField(blank=True)),
                ('ultima_movimentacao', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('posicionamento_fnp', models.TextField(blank=True)),
                ('acoes_incidencia', models.TextField(blank=True)),
                ('riscos_oportunidades', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('macrotema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposicoes', to='legislativo.macrotema')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposicoes', to='legislativo.tema')),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('resumo', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='legislativo.proposicao')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='EdicaoMeritoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=64)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edicoes_merito', to=settings.AUTH_USER_MODEL)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_edicoes', to='legislativo.proposicao')),
            ],
            options={
                'verbose_name': 'Histórico de edição de mérito',
                'verbose_name_plural': 'Históricos de edição de mérito',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('status_moderacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='legislativo.comentario')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='legislativo.proposicao')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='legislativo.municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
