# Generated by Django 4.2.30 on 2026-07-30 14:41, hand-edited to preserve data.

import re

from django.db import migrations, models
from django.utils.text import slugify


def populate_temas_m2m(apps, schema_editor):
    Proposicao = apps.get_model("legislativo", "Proposicao")
    Tema = apps.get_model("legislativo", "Tema")

    for proposicao in Proposicao.objects.exclude(tema__isnull=True):
        nomes = [parte.strip() for parte in re.split(r"[,/]", proposicao.tema.nome) if parte.strip()]
        temas = []
        for nome in nomes:
            tema, _ = Tema.objects.get_or_create(nome=nome, defaults={"slug": slugify(nome)})
            temas.append(tema)
        proposicao.temas.set(temas)

    # Remove os antigos registros de Tema com nomes compostos (ex.: "Clima,
    # Cidades, Desenvolvimento Urbano") que ficaram sem nenhuma proposição
    # associada depois da divisão acima.
    Tema.objects.filter(proposicoes__isnull=True).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("legislativo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposicao",
            name="temas",
            field=models.ManyToManyField(
                blank=True, related_name="proposicoes", to="legislativo.tema"
            ),
        ),
        migrations.RunPython(populate_temas_m2m, noop_reverse),
        migrations.RemoveField(
            model_name="proposicao",
            name="tema",
        ),
    ]
