# Generated by Django 4.2.30 on 2026-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislativo", "0002_replace_tema_with_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposicao",
            name="visualizacoes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
