# Generated by Django 4.2.30 on 2026-07-30 18:59, reordenada manualmente para
# criar Perfil e copiar os dados de Usuario ANTES de remover os campos antigos.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copiar_dados_para_perfil(apps, schema_editor):
    Usuario = apps.get_model('legislativo', 'Usuario')
    Perfil = apps.get_model('legislativo', 'Perfil')
    for usuario in Usuario.objects.all():
        Perfil.objects.get_or_create(
            usuario=usuario,
            defaults={
                'municipio_id': usuario.municipio_id,
                'telefone': usuario.telefone,
                'cargo': usuario.cargo,
            },
        )


def copiar_dados_de_volta_para_usuario(apps, schema_editor):
    Usuario = apps.get_model('legislativo', 'Usuario')
    Perfil = apps.get_model('legislativo', 'Perfil')
    for perfil in Perfil.objects.all():
        Usuario.objects.filter(pk=perfil.usuario_id).update(
            municipio_id=perfil.municipio_id,
            telefone=perfil.telefone,
            cargo=perfil.cargo,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("legislativo", "0004_notificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=32)),
                ("cargo", models.CharField(blank=True, max_length=255)),
                (
                    "municipio",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfil",
                        to="legislativo.municipio",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
        migrations.RunPython(copiar_dados_para_perfil, copiar_dados_de_volta_para_usuario),
        migrations.RemoveField(
            model_name="usuario",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
    ]
