# Generated by Django 4.2.30 on 2026-07-30 19:13, envolvida manualmente em
# SeparateDatabaseAndState: estes models foram divididos em apps.usuarios,
# apps.proposicoes e apps.comentarios (ver migrações iniciais desses apps).
# As tabelas físicas legislativo_* continuam existindo e com os mesmos
# dados — aqui só o ESTADO do Django é atualizado (o app legislativo deixa
# de "possuir" esses models), nenhuma DDL real roda (database_operations=[]).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legislativo", "0005_usuario_perfil_split"),
        ("usuarios", "0001_initial"),
        ("proposicoes", "0002_initial"),
        ("comentarios", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="comentario",
                    name="autor",
                ),
                migrations.RemoveField(
                    model_name="comentario",
                    name="parent",
                ),
                migrations.RemoveField(
                    model_name="comentario",
                    name="proposicao",
                ),
                migrations.RemoveField(
                    model_name="edicaomeritohistorico",
                    name="autor",
                ),
                migrations.RemoveField(
                    model_name="edicaomeritohistorico",
                    name="proposicao",
                ),
                migrations.RemoveField(
                    model_name="noticia",
                    name="proposicao",
                ),
                migrations.RemoveField(
                    model_name="notificacao",
                    name="comentario",
                ),
                migrations.RemoveField(
                    model_name="notificacao",
                    name="destinatario",
                ),
                migrations.RemoveField(
                    model_name="notificacao",
                    name="proposicao",
                ),
                migrations.DeleteModel(
                    name="Participacao",
                ),
                migrations.RemoveField(
                    model_name="perfil",
                    name="municipio",
                ),
                migrations.RemoveField(
                    model_name="perfil",
                    name="usuario",
                ),
                migrations.RemoveField(
                    model_name="proposicao",
                    name="macrotema",
                ),
                migrations.RemoveField(
                    model_name="proposicao",
                    name="temas",
                ),
                migrations.RemoveField(
                    model_name="tema",
                    name="macrotema",
                ),
                migrations.RemoveField(
                    model_name="usuario",
                    name="groups",
                ),
                migrations.RemoveField(
                    model_name="usuario",
                    name="user_permissions",
                ),
                migrations.DeleteModel(
                    name="Comentario",
                ),
                migrations.DeleteModel(
                    name="EdicaoMeritoHistorico",
                ),
                migrations.DeleteModel(
                    name="Macrotema",
                ),
                migrations.DeleteModel(
                    name="Municipio",
                ),
                migrations.DeleteModel(
                    name="Noticia",
                ),
                migrations.DeleteModel(
                    name="Notificacao",
                ),
                migrations.DeleteModel(
                    name="Perfil",
                ),
                migrations.DeleteModel(
                    name="Proposicao",
                ),
                migrations.DeleteModel(
                    name="Tema",
                ),
                migrations.DeleteModel(
                    name="Usuario",
                ),
            ],
            database_operations=[],
        ),
    ]
